
public enum Status {
    START,
    PLAYER_NAME_DECISION,
    GAME,
    GAME_ITEMGET,
    MENU,
    MENU_ITEM,
    MENU_STATUS,
    MENU_SAVE,
    MENU_TERMINATION,
    BATTLE,
    BATTLE_COMMAND,
    BATTLE_MESSAGE1,
    BATTLE_MESSAGE2,
    BATTLE_MESSAGE3,
    BATTLE_MESSAGE4,
    GAME_OVER
}
